"""
Synthetic history generator for ARIA's controlled experiment.

Generates N realistic past tutoring sessions matching the synthetic student profile,
then seeds them into ChromaDB and the learning graph so ARIA starts "pre-warmed"
with N sessions of history — as if it had been tutoring Alex Chen for real.

Each session is generated by llama3.1:8b using the profile's behavioral parameters.
Sessions are saved to data/synthetic_history.jsonl for reproducibility.
"""

import json
import random
import time
from dataclasses import asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Optional

import ollama

DATA_DIR = Path(__file__).parent.parent / "data"
DATA_DIR.mkdir(exist_ok=True)
HISTORY_LOG = DATA_DIR / "synthetic_history.jsonl"


# ------------------------------------------------------------------
# Session generator (LLM-backed)
# ------------------------------------------------------------------

_SESSION_GEN_SYSTEM = """You are generating a realistic past tutoring session between an ADHD student and their AI tutor ARIA.

Student profile:
  Name: {name}, Age: {age}, Diagnosis: {diagnosis}
  Subject this session: {subject}
  Topic: {topic}
  Known misconception: {misconception}
  Preferred style: {preferred_style}
  Behavioral tendency: {behavior}
  Starting confidence in this topic: {confidence:.0%}

Generate EXACTLY {n_turns} turns of dialogue. Format as JSON array:
[
  {{"role": "student", "content": "..."}},
  {{"role": "tutor", "content": "..."}},
  ...
]

Rules:
- Student messages must show the misconception naturally at least once
- Tutor uses the preferred style (step_by_step = numbered micro-steps, analogy = metaphors, visual = describe visually)
- Student should end with slightly higher understanding than they started (δ confidence = +0.05 to +0.15)
- Max 3 sentences per tutor paragraph
- Include at least one frustration phrase from the student if confidence < 0.45
- Output ONLY the JSON array, no other text"""

_TOPICS: dict = {
    "algebra": [
        ("linear equations", "drops negative signs when moving terms", 0.35),
        ("order of operations", "distributes addition before multiplication", 0.30),
        ("word problems", "doesn't identify the variable correctly", 0.25),
        ("factoring", "forgets to find GCF first", 0.40),
    ],
    "biology": [
        ("mitosis vs meiosis", "confuses the number of daughter cells produced", 0.50),
        ("cell division", "thinks all cells divide at the same rate", 0.45),
        ("DNA replication", "confuses leading and lagging strand synthesis", 0.55),
        ("protein synthesis", "confuses transcription and translation", 0.40),
    ],
    "python programming": [
        ("for loops", "off-by-one in range()", 0.45),
        ("variable scope", "confuses local and global scope", 0.40),
        ("conditionals", "doesn't chain elif correctly", 0.50),
        ("functions", "thinks modifying a parameter changes the caller's variable", 0.35),
    ],
}

_BEHAVIORS = {
    "low_confidence": "Student is hesitant, uses lots of hedging ('I think...', 'maybe...')",
    "confused": "Student asks clarifying questions, shows the misconception in their phrasing",
    "improving": "Student starts confused but starts connecting ideas by turn 4+",
    "frustrated": "Student uses short responses, 'idk', 'this is hard', but keeps trying",
}


def _generate_session(
    profile_dict: dict,
    subject: str,
    session_idx: int,
    n_turns: int = 5,
) -> Optional[List[dict]]:
    """Generate one synthetic tutoring session as a list of {role, content} dicts."""
    topics = _TOPICS.get(subject, _TOPICS["algebra"])
    topic, misconception, base_conf = topics[session_idx % len(topics)]

    # Adjust confidence with some noise
    confidence = max(0.1, min(0.9, base_conf + random.uniform(-0.1, 0.1)))
    behavior_key = "frustrated" if confidence < 0.35 else ("confused" if confidence < 0.50 else "improving")
    behavior = _BEHAVIORS[behavior_key]

    preferred_style = profile_dict.get("preferred_styles", {}).get(subject, "step_by_step")

    prompt = _SESSION_GEN_SYSTEM.format(
        name=profile_dict.get("name", "Alex"),
        age=profile_dict.get("age", 16),
        diagnosis=profile_dict.get("diagnosis", "ADHD-Combined"),
        subject=subject,
        topic=topic,
        misconception=misconception,
        preferred_style=preferred_style,
        behavior=behavior,
        confidence=confidence,
        n_turns=n_turns * 2,  # n_turns student + n_turns tutor
    )

    try:
        result = ollama.chat(
            model="llama3.1:8b",
            messages=[{"role": "user", "content": prompt}],
            options={"temperature": 0.75, "num_predict": 1500},
        )
        raw = result.message.content.strip()
        # Extract the JSON array — find the outermost [...] block
        start = raw.find("[")
        end = raw.rfind("]")
        if start == -1 or end == -1 or end <= start:
            return None
        parsed = json.loads(raw[start : end + 1])
        if isinstance(parsed, dict):
            for key in ("turns", "dialogue", "conversation", "messages"):
                if key in parsed:
                    parsed = parsed[key]
                    break
        if not isinstance(parsed, list):
            return None
        # Normalise roles
        turns = []
        for item in parsed:
            role = item.get("role", "").lower()
            content = item.get("content", "").strip()
            if role in ("student", "user"):
                turns.append({"role": "user", "content": content})
            elif role in ("tutor", "aria", "assistant"):
                turns.append({"role": "assistant", "content": content})
        return turns if len(turns) >= 4 else None

    except Exception:
        import traceback
        traceback.print_exc()
        return None


# ------------------------------------------------------------------
# Confidence delta estimation
# ------------------------------------------------------------------

def _estimate_confidence_delta(turns: List[dict]) -> float:
    """Heuristic: presence of success phrases vs confusion phrases."""
    success = ["oh ok", "that makes sense", "ohhhh", "i get it", "got it", "makes sense now"]
    frustration = ["idk", "don't get", "doesn't make sense", "confused", "forget it", "ugh"]
    student_text = " ".join(
        t["content"].lower() for t in turns if t["role"] == "user"
    )
    s_count = sum(1 for w in success if w in student_text)
    f_count = sum(1 for w in frustration if w in student_text)
    return round(max(-0.1, min(0.15, (s_count - f_count) * 0.03 + 0.05)), 3)


# ------------------------------------------------------------------
# Main seeding function
# ------------------------------------------------------------------

def seed_history(
    vector_store,
    learning_graph,
    profile,
    n_sessions: int = 10,
    verbose: bool = True,
) -> List[dict]:
    """
    Generate and seed N synthetic past sessions into ARIA's memory.

    Args:
        vector_store: VectorStore instance
        learning_graph: LearningGraph instance
        profile: SyntheticProfile or dict (from profile_as_aria_profile)
        n_sessions: how many sessions to generate
        verbose: print progress

    Returns:
        List of session metadata dicts (also saved to data/synthetic_history.jsonl)
    """
    if hasattr(profile, "subjects"):
        # SyntheticProfile dataclass
        profile_dict = {
            "name": profile.name,
            "age": profile.age,
            "diagnosis": profile.diagnosis,
            "subjects": profile.subjects,
            "preferred_styles": profile.preferred_styles,
            "frustration_triggers": getattr(profile, "frustration_triggers", {}),
        }
        subjects = profile.subjects
    else:
        # plain dict
        profile_dict = profile
        subjects = profile.get("subjects", ["algebra", "biology", "python programming"])

    # Normalise subject names (remove spaces for graph keys)
    subject_keys = [s.replace(" ", "_").lower() for s in subjects]

    sessions_meta = []
    now = datetime.now()

    # Clear existing synthetic history log
    open(HISTORY_LOG, "w").close()

    for i in range(n_sessions):
        subject_raw = subjects[i % len(subjects)]
        subject_key = subject_keys[i % len(subject_keys)]

        # Timestamp spread over past 30 days, weighted toward more recent
        days_ago = int(random.betavariate(1, 3) * 30)
        session_ts = now - timedelta(days=days_ago, hours=random.randint(20, 23))

        if verbose:
            print(f"  [seed] Generating session {i+1}/{n_sessions}: {subject_raw}", end="  ", flush=True)

        turns = _generate_session(
            profile_dict=profile_dict,
            subject=subject_raw,
            session_idx=i,
            n_turns=random.randint(3, 6),
        )

        if not turns:
            # Fallback: shorter session to avoid token truncation
            turns = _generate_session(
                profile_dict=profile_dict,
                subject=subject_raw,
                session_idx=i,
                n_turns=3,
            )

        if not turns:
            if verbose:
                print("SKIP (generation failed)")
            continue

        # Pair up turns and store in ChromaDB
        frustration_turns = 0
        topics_found = [subject_key]

        for j in range(0, len(turns) - 1, 2):
            user_turn = turns[j]
            assistant_turn = turns[j + 1] if j + 1 < len(turns) else None
            if not assistant_turn:
                break

            user_text = user_turn["content"]
            asst_text = assistant_turn["content"]

            # Simple frustration detection for this turn
            frustrated = any(
                w in user_text.lower()
                for w in ["idk", "don't get", "confused", "ugh", "doesn't make sense", "forget it"]
            )
            if frustrated:
                frustration_turns += 1

            style = profile_dict.get("preferred_styles", {}).get(subject_raw, "step_by_step")

            vector_store.store_turn(
                user_msg=user_text,
                assistant_msg=asst_text,
                topics=topics_found,
                frustration=frustrated,
                explanation_style=style,
                timestamp=session_ts,
            )

        # Update learning graph
        confidence_delta = _estimate_confidence_delta(turns)
        struggled = frustration_turns > 1

        # Ensure topic exists and update it
        learning_graph.ensure_topic(subject_key)
        learning_graph.record_study(
            topic=subject_key,
            struggled=struggled,
            explanation_style=profile_dict.get("preferred_styles", {}).get(subject_raw, "step_by_step"),
            was_helpful=confidence_delta > 0,
            hour=session_ts.hour,
        )

        # Session metadata
        meta = {
            "session_idx": i,
            "subject": subject_raw,
            "subject_key": subject_key,
            "timestamp": session_ts.isoformat(),
            "n_turns": len(turns),
            "frustration_turns": frustration_turns,
            "confidence_delta": confidence_delta,
            "turns": turns,
        }
        sessions_meta.append(meta)

        with open(HISTORY_LOG, "a") as f:
            f.write(json.dumps(meta) + "\n")

        if verbose:
            print(f"turns={len(turns)}  Δconf={confidence_delta:+.2f}  frustrated={frustrated}")

        # Avoid hammering Ollama
        time.sleep(0.3)

    if verbose:
        print(f"\n[seed] Seeded {len(sessions_meta)}/{n_sessions} sessions into memory.")

    return sessions_meta


# ------------------------------------------------------------------
# Convenience: seed_history_n for N in [0, 5, 10, 20]
# ------------------------------------------------------------------

def seed_history_n(
    vector_store,
    learning_graph,
    profile,
    n: int,
    verbose: bool = False,
) -> List[dict]:
    """Seed exactly N sessions. Wrapper around seed_history."""
    if n == 0:
        return []
    return seed_history(vector_store, learning_graph, profile, n_sessions=n, verbose=verbose)


# ------------------------------------------------------------------
# CLI
# ------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))

    from eval.profiles import ProfileVectorStore, ProfileLearningGraph
    from eval.synthetic_profile import ALEX_CHEN

    n = int(sys.argv[1]) if len(sys.argv) > 1 else 10
    print(f"Seeding {n} synthetic history sessions for {ALEX_CHEN.name}...")

    vs = ProfileVectorStore(ALEX_CHEN.profile_id)
    lg = ProfileLearningGraph(ALEX_CHEN.profile_id)

    seed_history(vs, lg, ALEX_CHEN, n_sessions=n, verbose=True)
    print(f"\nHistory saved to {HISTORY_LOG}")
